import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <nav className="flex w-full items-center justify-between p-4 text-xl border-b">
      <div className="text-2xl">
        <a href="/" className="mx-2">
          Ale
        </a>
      </div>
      <div>
        <a href="#" className="mx-2">
          Gallery
        </a>
        <a href="#" className="mx-2">
          About
        </a>
        <a href="/signin" className="mx-2">
          Sign in
        </a>
        <a href="#" className="mx-2">
          Credits
        </a>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className={`font-sans flex flex-col gap-4`}>
        <TopNav />
        {children}
      </body>
    </html>
  );
}
